<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USER-20170324KF" name="com.fkapi.excutecase.ExcuteYiCaiCase" tests="2" failures="0" timestamp="20 Jun 2017 08:00:07 GMT" time="68.807" errors="1">
  <testcase name="excute" time="33.512" classname="com.fkapi.excutecase.ExcuteYiCaiCase">
    <error type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at message : expected [AUDIT_PASS] but found [AUDIT_RETURN] in method : .excute(ExcuteYiCaiCase:92)
	at com.fkapi.excutecase.ExcuteYiCaiCase.excute(ExcuteYiCaiCase.java:92)
]]>
    </error>
  </testcase> <!-- excute -->
  <testcase name="excute" time="35.295" classname="com.fkapi.excutecase.ExcuteYiCaiCase"/>
</testsuite> <!-- com.fkapi.excutecase.ExcuteYiCaiCase -->
